# Generated by Django 4.1.4 on 2023-07-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_todo_todo_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='todo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
